#! /usr/bin/env python
# -*- encoding:utf-8 -*-

"""
Usage:
    zen-run reset
    zen-run initialize
    zen-run configure <username> [-s <share> -f <fund> -t <threshold> -e <excludes>]
    zen-run configure [-c <currency> -b <block-delay>]
    zen-run start-tbw
    zen-run stop-tbw
    zen-run launch-payroll <username>
    zen-run resume-payroll <username>

Options:
-b --block-delay=<block-delay>
-c --currency=<currency>
-e --excludes=<excludes>
-f --funds=<address>
-s --share=<amount>
-t --threshold=<threshold>
"""

import os
import sys
import optparse

sys.path.append(os.path.abspath(os.path.expanduser("~/zen")))

import zen
import docopt
import zen.tbw


def _addresses(value):
	if os.path.exists(value):
		with io.open(value, "r") as data:
			return [addr.strip() for addr in data.read().split("\n").split(",")]
	else:
		return value.split(",")

FILTER = {
	"--block-delay": lambda value: int(value),
	"--currency":    lambda value: str(value),
	"--excludes":    lambda value: _addresses(value),
	"--funds":       lambda value: str(value),
	"--share":       lambda value: min(1.0, float(value)),
	"--threshold":   lambda value: float(value),
}


def start_tbw(args={}, **options):
	os.system("""
if [ "$(pm2 id zen-tbw) " = "[] " ]; then
	cd %(abspath)s
    pm2 start app.json
else
    pm2 restart zen-tbw
fi
""" % {"abspath": os.path.abspath(os.path.dirname(__file__))}
)


def stop_tbw(args={}, **options):
	os.chdir(os.path.abspath(os.path.dirname(__file__)))
	os.system("""
if [ "$(pm2 id zen-tbw) " != "[] " ]; then
	cd %(abspath)s
    pm2 stop zen-tbw
fi
""" % {"abspath": os.path.abspath(os.path.dirname(__file__))}
)


def reset(args={}, **options):
	os.remove(os.path.join(zen.JSON, "root.json"))
	initialize(args, **options)


def initialize(args={}, **options):
	zen.init()
	zen.tbw.init()


def launch_payroll(args={}, **options):
	username = args["<username>"]
	zen.tbw.extract(username)
	zen.tbw.dumpRegistry(username)
	zen.tbw.broadcast(username)


def resume_payroll(args={}, **options):
	username = args["<username>"]
	zen.tbw.dumpRegistry(username)
	zen.tbw.broadcast(username)


def configure(args={}, **options):
	username = args["<username>"]
	if username:
		zen.tbw.init(username=username, **options)
	else:
		zen.tbw.init()
	

def adjust(args={}, **options):
	username = args["<username>"]
	zen.tbw.adjust(username, options["value"])


if __name__ == "__main__":
	tbw = zen.loadJson("tbw.json")

	def getAction(args):
		for action in [k for k in args if k[0] not in ["-", "<"]]:
			if args[action] == True:
				return action
		return False

	def getOptions(args):
		options = {}
		for option,value in [(k,v) for k,v in args.items() if k.startswith("--") and v != None]:
			options[option[2:].replace("-", "_")] = FILTER[option](value)
		return options

	args = docopt.docopt(__doc__, argv=sys.argv[1:])
	action = getAction(args)
	options = getOptions(args)

	if action:
		func = getattr(sys.modules[__name__], action.replace("-", "_"))
		if callable(func):
			func(args, **options)
